setwd('F:\\Bingbin\\capstone')
source('util.r')
pkg()
print('Loading training data')
rawTrain <- read.csv('train.csv')
print('Loading testing data')
rawTest <- read.csv('test.csv')
print('Preprocessing training data')
dtrain <- preCat(rawTrain, T)
print('Preprocessing testing data')
dtest <- preCat(rawTest, F)
print('Setup completed.')
print('head(dtrain, n=2):')
head(dtrain, n=2)
print('head(dtest, n=2):')
head(dtest, n=2)
